name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/backend
      IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build -t $IMAGE_BACKEND:latest ./backend
          docker push $IMAGE_BACKEND:latest

      - name: Build frontend Docker image
        run: |
          docker build -t $IMAGE_FRONTEND:latest ./frontend
          docker push $IMAGE_FRONTEND:latest
